config/routes.rb
Rails.application.routes.draw do
  resources :arguments

  resources :articles
  devise_for :users

  root "articles#index"

  post "articles/suggestions", to: "articles#suggestions", as: :suggestions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/argument.rb
class Argument < ApplicationRecord

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :title, length: { minimum: 3 }

  scope :search, -> (query = '') { where('lower(title) LIKE ?', "%#{query.downcase}%") }
  
  scope :top, -> { order(score: :desc) }
  scope :most_searched, -> { order(search_count: :desc) }
  scope :least_searched, -> { order(search_count: :asc) }

  after_save :broadcast_update

  LIMIT = 10

  def self.search_and_score(query)
    arguments = Argument.search(query)
    
    if arguments.present?
      arguments.each do |argument|
        if argument.title.downcase === query.downcase
          argument.increment!(:search_count)
          argument.save
        end
      end
    else
      if validate_query(query)
        puts "🔍 #{query}"
        save_new_argument(query)
      else 
        save_existing_argument(query)
      end
    end

    return arguments.most_searched

    puts "🔍 #{query}"
  end

  private

  def self.validate_query(query)
    if query.ends_with?('?') and (query.starts_with?('Why ', 'What ', 'How ', 'When ', 'Who ', 'Where ') || query.match?(/^[A-Z]/)) and query.count('?') == 1
      return true
    elsif query.ends_with?('!') and query.match?(/^[A-Z]/)
      return true
    elsif query.ends_with?('...') and query.match?(/^[A-Z]/)
      return true
    else
      return false
    end
  end

  def self.save_new_argument(query)
    Argument.new(title: query, search_count: 1).save
    puts "💾 #{query} saved."
  end

  def self.save_existing_argument(query)
    articles = Article.search(query)

    if articles.present?
      articles.each do |article|
        if article.title === query
          Argument.new(title: query, search_count: 1).save
          puts "💾 #{query}: exists article but not searched before."
        end
      end
    end
  end

  def update_score
    if self.search_count > 0
      self.score = self.search_count * 0.5
    else
      self.score = 1
    end
  end

  def broadcast_update
    arguments_html = ApplicationController.render(
      partial: "arguments/arguments",
      locals: { arguments: Argument.all.most_searched }
    )

    ActionCable.server.broadcast(
      "arguments_channel",
      {
        arguments_html: arguments_html,
      }
    )
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true

  scope :search, -> (query) { where('lower(title) LIKE ?', "%#{query.downcase}%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :set_argument, only: %i[ show edit update destroy ]

  # GET /arguments or /arguments.json
  def index
    @arguments = Argument.all.most_searched
  end

  # GET /arguments/1 or /arguments/1.json
  def show
  end

  # GET /arguments/new
  def new
    @argument = Argument.new
  end

  # GET /arguments/1/edit
  def edit
  end

  # POST /arguments or /arguments.json
  def create
    @argument = Argument.new(argument_params)

    respond_to do |format|
      if @argument.save
        puts "Argument was successfully created."
      else
        puts "Argument was not successfully created."
      end
    end
  end

  # PATCH/PUT /arguments/1 or /arguments/1.json
  def update
    respond_to do |format|
      if @argument.update(argument_params)
        format.html { redirect_to argument_url(@argument), notice: "Argument was successfully updated." }
        format.json { render :show, status: :ok, location: @argument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arguments/1 or /arguments/1.json
  def destroy
    @argument.destroy

    respond_to do |format|
      format.html { redirect_to arguments_url, notice: "Argument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_argument
      @argument = Argument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def argument_params
      params.fetch(:argument, {})
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    respond_to_index(params[:query])

    @arguments = Argument.most_searched
  end

  def suggestions
    respond_to_suggestions(params[:query])
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    unless current_user
      redirect_to new_user_session_path, notice: "You must be logged in to create an article."
      return
    end

    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end

    def respond_to_index(query)
      if query.present?
        @articles = Article.search(query)
  
        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: turbo_stream.update(
              "articles",
              partial: "articles/articles",
              locals: { articles: @articles }
            )
          }
          format.html { render :index }
        end
      else
         @articles = Article.all
      end
    end

    def respond_to_suggestions(query)
      if query.present?
        @arguments = Argument.search_and_score(query).most_searched

        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: turbo_stream.update(
              "arguments",
              partial: "articles/arguments",
              locals: { arguments: @arguments }
            )
          }
          format.html { render :arguments }
        end
      else
        @arguments = Argument.most_searched
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/arguments/_argument.html.erb
<div id="<%= dom_id argument %>">
  <%= argument.title %>
  <%= link_to "delete", argument, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/arguments/_arguments.html.erb
<% if arguments.any? %>
  <% arguments.each do |argument| %>
    <tr>
      <td><%= argument.title %></td>
      <td><%= argument.search_count %></td>
      <td><%= argument.score %></td>
    </tr>
  <% end %>
<% end %>

app/views/arguments/_form.html.erb
<%= form_with(model: argument) do |form| %>
  <% if argument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(argument.errors.count, "error") %> prohibited this argument from being saved:</h2>

      <ul>
        <% argument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/arguments/edit.html.erb
<h1>Editing argument</h1>

<%= render "form", argument: @argument %>

<br>

<div>
  <%= link_to "Show this argument", @argument %> |
  <%= link_to "Back to arguments", arguments_path %>
</div>

app/views/arguments/index.html.erb
<%# table: argument:title, argument:search_count, argument:score %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Search Count</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody data-controller="arguments" id="arguments-table">
    <% @arguments.each do |argument| %>
      <tr>
        <td><%= argument.title %></td>
        <td><%= argument.search_count %></td>
        <td><%= argument.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= turbo_stream_from "quotes" %>

app/views/arguments/new.html.erb
<h1>New argument</h1>

<%= render "form", argument: @argument %>

<br>

<div>
  <%= link_to "Back to arguments", arguments_path %>
</div>

app/views/arguments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @argument %>

<div>
  <%= link_to "Edit this argument", edit_argument_path(@argument) %> |
  <%= link_to "Back to arguments", arguments_path %>

  <%= button_to "Destroy this argument", @argument, method: :delete %>
</div>

app/views/articles/_arguments.html.erb
<% if arguments %>
  <ul>
    <% arguments.each do |argument| %>
      <% if Article.find_by(title: argument.title) %>
        <% article = Article.find_by(title: argument.title) %>
        <li><%= link_to article.title, article_path(article) %></li>
      <% else %>
        <li><%= argument.title %></li>
      <% end %>
    <% end %>
  </ul>
<% end%>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="article">
  <p>
    <%= link_to article.title, article %>
  </p>
</div>

app/views/articles/_articles.html.erb
<ul>
  <% articles.each do |article| %>
    <li><%= article.title %></li>
  <% end %>
</ul>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :content %>
    <%= form.text_area :content %>

    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Articles</h1>

<div class="search">
  <%= form_with(url: articles_path, method: :get, 
  data: {
    action: "keyup->search#arguments",
    controller: "search",
    suggesttions_url: suggestions_path,
    }, 
    id: "search-form"
    
    ) do |form| %>
    <%= form.text_field :query, placeholder: "Search articles", data: {
      search_target: "query",
      action: "blur->search#hideArguments"}, autocomplete: :off, id: current_user.id, class: "search-input" %>

    <%= form.submit "Search" %>

    <div id="arguments" data-search-target="arguments" data-action="mousedown->search#childClicked">
      <%= render partial: "articles/arguments", locals: { arguments: @arguments } %>
    </div>
  <% end %>
</div>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearchBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>